// Code generated by "stringer -type=tileKind"; DO NOT EDIT.

package s11

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unset-0]
	_ = x[floorTile-1]
	_ = x[emptySeat-2]
	_ = x[occupiedSeat-3]
	_ = x[observer-4]
}

const _tileKind_name = "unsetfloorTileemptySeatoccupiedSeatobserver"

var _tileKind_index = [...]uint8{0, 5, 14, 23, 35, 43}

func (i tileKind) String() string {
	if i < 0 || i >= tileKind(len(_tileKind_index)-1) {
		return "tileKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tileKind_name[_tileKind_index[i]:_tileKind_index[i+1]]
}
