// Code generated by "stringer -type=Cmd"; DO NOT EDIT.

package s14

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mask-1]
	_ = x[write-2]
}

const _Cmd_name = "maskwrite"

var _Cmd_index = [...]uint8{0, 4, 9}

func (i Cmd) String() string {
	i -= 1
	if i < 0 || i >= Cmd(len(_Cmd_index)-1) {
		return "Cmd(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Cmd_name[_Cmd_index[i]:_Cmd_index[i+1]]
}
