// Code generated by "stringer -type=Command"; DO NOT EDIT.

package s12

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[moveForward-1]
	_ = x[rotRight-2]
	_ = x[rotLeft-3]
	_ = x[moveNorth-4]
	_ = x[moveSouth-5]
	_ = x[moveEast-6]
	_ = x[moveWest-7]
}

const _Command_name = "moveForwardrotRightrotLeftmoveNorthmoveSouthmoveEastmoveWest"

var _Command_index = [...]uint8{0, 11, 19, 26, 35, 44, 52, 60}

func (i Command) String() string {
	i -= 1
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
